<?php

  function weather_api_theme($existing, $type, $theme, $path) {
    return [
      'weather_api' => [
        'variables' => ['items' => [], 
                        'title' => '', 
                        'nombre' => '', 
                        'listaciudades' => '',
                        'apiendpoint' => '',
                        'apitoken' => '',
                        'hayciudades' => '',
                        'isapicomplete' => '' ]
      ]
    ];
  }



