<?php


// function weather_api_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
//     ksm($form_id);
//     // if($form_id == 'comment_form'){
//     //   $form['actions']['submit']['#value'] = t('Comentarrrrr');
//     // }
//   }

/**
 * Implement hook_theme().
 */
function weather_api_theme($existing, $type, $theme, $path) {
  return [
    'weather_api' => [
      'variables' => ['items' => [], 'title' => '', 'nombre' => '', 'listaciudades' => '' ]
    ]
  ];
}



